"""DialectsOnX-only UI strings. Agent-written; do not call Gemini/Vertex.

Reuse Android pack keys at runtime (lens_view_original, label_dialect_selector,
home_settings, pad_faw_*, ime_*, settings_*, system_language_*, dialect_*, …).
This file is only keys Android packs lack.
Brand tokens Dialex, DialectsOnX, Pad, and MSA stay Latin.
"""

from __future__ import annotations

# English SoT. Placeholders match Android (%1$s).
DELTA_EN: dict[str, str] = {
    "dox_show_more": "Show more",
    "dox_ime": "IME",
    "dox_ime_show": "Show IME",
    "dox_ime_collapse": "Collapse",
    "dox_on": "On",
    "dox_off": "Off",
    "dox_auto_translate": "Auto-translate",
    "dox_news_to_msa": "News → MSA",
    "dox_backend_url": "Backend URL",
    "dox_ime_remember": "Remember IME position",
    "dox_ime_enabled": "Show IME bar",
    "dox_open_pad": "Dialex Pad",
    "dox_rate_limited": "Rate limited. Try again later.",
    "dox_addressee": "Addressee you",
    "dox_clear_recents": "Clear Recents",
    "dox_about_line": "DialectsOnX %1$s",
    "dox_status_ready": "Ready",
    "dox_status_error": "Couldn't translate",
    "dox_skip_field": "Can't translate this field",
    "dox_default_dialect": "Default dialect",
    "dox_advanced": "Advanced",
    "dox_ime_idle": "Ready",
    "dox_translate_failed": "Couldn't translate",
}

# dialect_id → strings. english_american is DELTA_EN.
# Compact chrome: keep density close to English. Brands stay Latin.
DELTA_BY_DIALECT: dict[str, dict[str, str]] = {
    "spanish_castilian": {
        "dox_show_more": "Mostrar más",
        "dox_ime": "IME",
        "dox_ime_show": "Mostrar IME",
        "dox_ime_collapse": "Cerrar",
        "dox_on": "Activado",
        "dox_off": "Desactivado",
        "dox_auto_translate": "Traducir auto",
        "dox_news_to_msa": "Noticias → MSA",
        "dox_backend_url": "URL del backend",
        "dox_ime_remember": "Recordar posición del IME",
        "dox_ime_enabled": "Mostrar barra IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Límite alcanzado. Prueba más tarde.",
        "dox_addressee": "Destinatario tú",
        "dox_clear_recents": "Borrar recientes",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Listo",
        "dox_status_error": "No se pudo traducir",
        "dox_skip_field": "No se puede traducir este campo",
        "dox_default_dialect": "Dialecto predeterminado",
        "dox_advanced": "Avanzado",
        "dox_ime_idle": "Listo",
        "dox_translate_failed": "No se pudo traducir",
    },
    "portuguese_lisbon": {
        "dox_show_more": "Mostrar mais",
        "dox_ime": "IME",
        "dox_ime_show": "Mostrar IME",
        "dox_ime_collapse": "Fechar",
        "dox_on": "Ligado",
        "dox_off": "Desligado",
        "dox_auto_translate": "Traduzir auto",
        "dox_news_to_msa": "Notícias → MSA",
        "dox_backend_url": "URL do backend",
        "dox_ime_remember": "Lembrar posição do IME",
        "dox_ime_enabled": "Mostrar barra IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limite atingido. Tenta mais tarde.",
        "dox_addressee": "Destinatário tu",
        "dox_clear_recents": "Limpar recentes",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Pronto",
        "dox_status_error": "Não foi possível traduzir",
        "dox_skip_field": "Não dá para traduzir este campo",
        "dox_default_dialect": "Dialeto predefinido",
        "dox_advanced": "Avançado",
        "dox_ime_idle": "Pronto",
        "dox_translate_failed": "Não foi possível traduzir",
    },
    "french_parisian": {
        "dox_show_more": "Afficher plus",
        "dox_ime": "IME",
        "dox_ime_show": "Afficher l'IME",
        "dox_ime_collapse": "Réduire",
        "dox_on": "Activé",
        "dox_off": "Désactivé",
        "dox_auto_translate": "Traduction auto",
        "dox_news_to_msa": "Actu → MSA",
        "dox_backend_url": "URL du backend",
        "dox_ime_remember": "Mémoriser la position de l'IME",
        "dox_ime_enabled": "Afficher la barre IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Quota atteint. Réessaie plus tard.",
        "dox_addressee": "Destinataire toi",
        "dox_clear_recents": "Effacer les récents",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Prêt",
        "dox_status_error": "Traduction impossible",
        "dox_skip_field": "Impossible de traduire ce champ",
        "dox_default_dialect": "Dialecte par défaut",
        "dox_advanced": "Avancé",
        "dox_ime_idle": "Prêt",
        "dox_translate_failed": "Traduction impossible",
    },
    "italian_italy": {
        "dox_show_more": "Mostra altro",
        "dox_ime": "IME",
        "dox_ime_show": "Mostra IME",
        "dox_ime_collapse": "Chiudi",
        "dox_on": "Attivo",
        "dox_off": "Disattivo",
        "dox_auto_translate": "Traduci auto",
        "dox_news_to_msa": "Notizie → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Ricorda posizione IME",
        "dox_ime_enabled": "Mostra barra IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limite raggiunto. Riprova più tardi.",
        "dox_addressee": "Destinatario tu",
        "dox_clear_recents": "Cancella recenti",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Pronto",
        "dox_status_error": "Traduzione non riuscita",
        "dox_skip_field": "Impossibile tradurre questo campo",
        "dox_default_dialect": "Dialetto predefinito",
        "dox_advanced": "Avanzate",
        "dox_ime_idle": "Pronto",
        "dox_translate_failed": "Traduzione non riuscita",
    },
    "romanian_bucharest": {
        "dox_show_more": "Arată mai mult",
        "dox_ime": "IME",
        "dox_ime_show": "Arată IME",
        "dox_ime_collapse": "Restrânge",
        "dox_on": "Pornit",
        "dox_off": "Oprit",
        "dox_auto_translate": "Traducere auto",
        "dox_news_to_msa": "Știri → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Reține poziția IME",
        "dox_ime_enabled": "Arată bara IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limită atinsă. Încearcă mai târziu.",
        "dox_addressee": "Destinatar tu",
        "dox_clear_recents": "Șterge recente",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Gata",
        "dox_status_error": "Nu s-a putut traduce",
        "dox_skip_field": "Nu se poate traduce acest câmp",
        "dox_default_dialect": "Dialect implicit",
        "dox_advanced": "Avansat",
        "dox_ime_idle": "Gata",
        "dox_translate_failed": "Nu s-a putut traduce",
    },
    "german_germany": {
        "dox_show_more": "Mehr anzeigen",
        "dox_ime": "IME",
        "dox_ime_show": "IME zeigen",
        "dox_ime_collapse": "Einklappen",
        "dox_on": "An",
        "dox_off": "Aus",
        "dox_auto_translate": "Auto-übersetzen",
        "dox_news_to_msa": "News → MSA",
        "dox_backend_url": "Backend-URL",
        "dox_ime_remember": "IME-Position merken",
        "dox_ime_enabled": "IME-Leiste zeigen",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit erreicht. Später erneut versuchen.",
        "dox_addressee": "Adressat du",
        "dox_clear_recents": "Zuletzt verwendet löschen",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Bereit",
        "dox_status_error": "Übersetzung fehlgeschlagen",
        "dox_skip_field": "Dieses Feld nicht übersetzbar",
        "dox_default_dialect": "Standarddialekt",
        "dox_advanced": "Erweitert",
        "dox_ime_idle": "Bereit",
        "dox_translate_failed": "Übersetzung fehlgeschlagen",
    },
    "dutch_netherlands": {
        "dox_show_more": "Meer tonen",
        "dox_ime": "IME",
        "dox_ime_show": "IME tonen",
        "dox_ime_collapse": "Inklappen",
        "dox_on": "Aan",
        "dox_off": "Uit",
        "dox_auto_translate": "Auto-vertalen",
        "dox_news_to_msa": "Nieuws → MSA",
        "dox_backend_url": "Backend-URL",
        "dox_ime_remember": "IME-positie onthouden",
        "dox_ime_enabled": "IME-balk tonen",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limiet bereikt. Probeer later opnieuw.",
        "dox_addressee": "Aangesprokene jij",
        "dox_clear_recents": "Recent wissen",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Klaar",
        "dox_status_error": "Vertalen mislukt",
        "dox_skip_field": "Dit veld kan niet vertaald",
        "dox_default_dialect": "Standaarddialect",
        "dox_advanced": "Geavanceerd",
        "dox_ime_idle": "Klaar",
        "dox_translate_failed": "Vertalen mislukt",
    },
    "mandarin_mainland": {
        "dox_show_more": "显示更多",
        "dox_ime": "IME",
        "dox_ime_show": "显示 IME",
        "dox_ime_collapse": "收起",
        "dox_on": "开",
        "dox_off": "关",
        "dox_auto_translate": "自动翻译",
        "dox_news_to_msa": "新闻 → MSA",
        "dox_backend_url": "后端网址",
        "dox_ime_remember": "记住 IME 位置",
        "dox_ime_enabled": "显示 IME 栏",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "已达上限。请稍后再试。",
        "dox_addressee": "称呼你",
        "dox_clear_recents": "清除最近使用",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "就绪",
        "dox_status_error": "无法翻译",
        "dox_skip_field": "无法翻译此字段",
        "dox_default_dialect": "默认方言",
        "dox_advanced": "高级",
        "dox_ime_idle": "就绪",
        "dox_translate_failed": "无法翻译",
    },
    "japanese_tokyo": {
        "dox_show_more": "さらに表示",
        "dox_ime": "IME",
        "dox_ime_show": "IMEを表示",
        "dox_ime_collapse": "閉じる",
        "dox_on": "オン",
        "dox_off": "オフ",
        "dox_auto_translate": "自動翻訳",
        "dox_news_to_msa": "ニュース → MSA",
        "dox_backend_url": "バックエンドURL",
        "dox_ime_remember": "IME位置を記憶",
        "dox_ime_enabled": "IMEバーを表示",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "制限に達しました。後で再試行。",
        "dox_addressee": "宛先のあなた",
        "dox_clear_recents": "最近を消去",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "準備完了",
        "dox_status_error": "翻訳できませんでした",
        "dox_skip_field": "この欄は翻訳できません",
        "dox_default_dialect": "デフォルト方言",
        "dox_advanced": "詳細",
        "dox_ime_idle": "準備完了",
        "dox_translate_failed": "翻訳できませんでした",
    },
    "korean_seoul": {
        "dox_show_more": "더 보기",
        "dox_ime": "IME",
        "dox_ime_show": "IME 표시",
        "dox_ime_collapse": "접기",
        "dox_on": "켜짐",
        "dox_off": "꺼짐",
        "dox_auto_translate": "자동 번역",
        "dox_news_to_msa": "뉴스 → MSA",
        "dox_backend_url": "백엔드 URL",
        "dox_ime_remember": "IME 위치 기억",
        "dox_ime_enabled": "IME 바 표시",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "한도에 도달했습니다. 나중에 다시 시도하세요.",
        "dox_addressee": "상대 너",
        "dox_clear_recents": "최근 항목 지우기",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "준비됨",
        "dox_status_error": "번역하지 못했습니다",
        "dox_skip_field": "이 필드는 번역할 수 없습니다",
        "dox_default_dialect": "기본 방언",
        "dox_advanced": "고급",
        "dox_ime_idle": "준비됨",
        "dox_translate_failed": "번역하지 못했습니다",
    },
    "russian_moscow": {
        "dox_show_more": "Показать ещё",
        "dox_ime": "IME",
        "dox_ime_show": "Показать IME",
        "dox_ime_collapse": "Свернуть",
        "dox_on": "Вкл",
        "dox_off": "Выкл",
        "dox_auto_translate": "Автоперевод",
        "dox_news_to_msa": "Новости → MSA",
        "dox_backend_url": "URL бэкенда",
        "dox_ime_remember": "Запомнить позицию IME",
        "dox_ime_enabled": "Показать панель IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Лимит исчерпан. Попробуйте позже.",
        "dox_addressee": "Адресат ты",
        "dox_clear_recents": "Очистить недавние",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Готово",
        "dox_status_error": "Не удалось перевести",
        "dox_skip_field": "Это поле нельзя перевести",
        "dox_default_dialect": "Диалект по умолчанию",
        "dox_advanced": "Дополнительно",
        "dox_ime_idle": "Готово",
        "dox_translate_failed": "Не удалось перевести",
    },
    "ukrainian_kyiv": {
        "dox_show_more": "Показати ще",
        "dox_ime": "IME",
        "dox_ime_show": "Показати IME",
        "dox_ime_collapse": "Згорнути",
        "dox_on": "Увімк",
        "dox_off": "Вимк",
        "dox_auto_translate": "Автопереклад",
        "dox_news_to_msa": "Новини → MSA",
        "dox_backend_url": "URL бекенду",
        "dox_ime_remember": "Запам’ятати позицію IME",
        "dox_ime_enabled": "Показати панель IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Ліміт вичерпано. Спробуйте пізніше.",
        "dox_addressee": "Адресат ти",
        "dox_clear_recents": "Очистити недавні",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Готово",
        "dox_status_error": "Не вдалося перекласти",
        "dox_skip_field": "Це поле не можна перекласти",
        "dox_default_dialect": "Діалект за замовчуванням",
        "dox_advanced": "Додатково",
        "dox_ime_idle": "Готово",
        "dox_translate_failed": "Не вдалося перекласти",
    },
    "polish_warsaw": {
        "dox_show_more": "Pokaż więcej",
        "dox_ime": "IME",
        "dox_ime_show": "Pokaż IME",
        "dox_ime_collapse": "Zwiń",
        "dox_on": "Wł.",
        "dox_off": "Wył.",
        "dox_auto_translate": "Auto-tłumacz",
        "dox_news_to_msa": "Wiadomości → MSA",
        "dox_backend_url": "URL backendu",
        "dox_ime_remember": "Zapamiętaj pozycję IME",
        "dox_ime_enabled": "Pokaż pasek IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit osiągnięty. Spróbuj później.",
        "dox_addressee": "Adresat ty",
        "dox_clear_recents": "Wyczyść ostatnie",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Gotowe",
        "dox_status_error": "Nie udało się przetłumaczyć",
        "dox_skip_field": "Tego pola nie da się przetłumaczyć",
        "dox_default_dialect": "Domyślny dialekt",
        "dox_advanced": "Zaawansowane",
        "dox_ime_idle": "Gotowe",
        "dox_translate_failed": "Nie udało się przetłumaczyć",
    },
    "czech_prague": {
        "dox_show_more": "Zobrazit víc",
        "dox_ime": "IME",
        "dox_ime_show": "Zobrazit IME",
        "dox_ime_collapse": "Sbalit",
        "dox_on": "Zapnuto",
        "dox_off": "Vypnuto",
        "dox_auto_translate": "Auto-překlad",
        "dox_news_to_msa": "Zprávy → MSA",
        "dox_backend_url": "URL backendu",
        "dox_ime_remember": "Zapamatovat polohu IME",
        "dox_ime_enabled": "Zobrazit lištu IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit dosažen. Zkus to později.",
        "dox_addressee": "Oslovený ty",
        "dox_clear_recents": "Vymazat nedávné",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Připraveno",
        "dox_status_error": "Nepodařilo se přeložit",
        "dox_skip_field": "Toto pole nelze přeložit",
        "dox_default_dialect": "Výchozí dialekt",
        "dox_advanced": "Pokročilé",
        "dox_ime_idle": "Připraveno",
        "dox_translate_failed": "Nepodařilo se přeložit",
    },
    "slovak_bratislava": {
        "dox_show_more": "Zobraziť viac",
        "dox_ime": "IME",
        "dox_ime_show": "Zobraziť IME",
        "dox_ime_collapse": "Zbaliť",
        "dox_on": "Zapnuté",
        "dox_off": "Vypnuté",
        "dox_auto_translate": "Auto-preklad",
        "dox_news_to_msa": "Správy → MSA",
        "dox_backend_url": "URL backendu",
        "dox_ime_remember": "Zapamätať polohu IME",
        "dox_ime_enabled": "Zobraziť lištu IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit dosiahnutý. Skús neskôr.",
        "dox_addressee": "Oslovený ty",
        "dox_clear_recents": "Vymazať nedávne",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Pripravené",
        "dox_status_error": "Nepodarilo sa preložiť",
        "dox_skip_field": "Toto pole sa nedá preložiť",
        "dox_default_dialect": "Predvolený dialekt",
        "dox_advanced": "Pokročilé",
        "dox_ime_idle": "Pripravené",
        "dox_translate_failed": "Nepodarilo sa preložiť",
    },
    "arabic_msa": {
        "dox_show_more": "عرض المزيد",
        "dox_ime": "IME",
        "dox_ime_show": "إظهار IME",
        "dox_ime_collapse": "طي",
        "dox_on": "تشغيل",
        "dox_off": "إيقاف",
        "dox_auto_translate": "ترجمة تلقائية",
        "dox_news_to_msa": "الأخبار → MSA",
        "dox_backend_url": "عنوان الخلفية",
        "dox_ime_remember": "تذكّر موضع IME",
        "dox_ime_enabled": "إظهار شريط IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "تم بلوغ الحد. حاول لاحقاً.",
        "dox_addressee": "المخاطَب أنت",
        "dox_clear_recents": "مسح الأخيرة",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "جاهز",
        "dox_status_error": "تعذّرت الترجمة",
        "dox_skip_field": "لا يمكن ترجمة هذا الحقل",
        "dox_default_dialect": "اللهجة الافتراضية",
        "dox_advanced": "متقدم",
        "dox_ime_idle": "جاهز",
        "dox_translate_failed": "تعذّرت الترجمة",
    },
    "hebrew_israel": {
        "dox_show_more": "הצג עוד",
        "dox_ime": "IME",
        "dox_ime_show": "הצג IME",
        "dox_ime_collapse": "כווץ",
        "dox_on": "פועל",
        "dox_off": "כבוי",
        "dox_auto_translate": "תרגום אוטומטי",
        "dox_news_to_msa": "חדשות → MSA",
        "dox_backend_url": "כתובת Backend",
        "dox_ime_remember": "זכור מיקום IME",
        "dox_ime_enabled": "הצג סרגל IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "הגעת למגבלה. נסה שוב מאוחר יותר.",
        "dox_addressee": "נמען אתה",
        "dox_clear_recents": "נקה אחרונים",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "מוכן",
        "dox_status_error": "לא ניתן לתרגם",
        "dox_skip_field": "אי אפשר לתרגם את השדה",
        "dox_default_dialect": "ניב ברירת מחדל",
        "dox_advanced": "מתקדם",
        "dox_ime_idle": "מוכן",
        "dox_translate_failed": "לא ניתן לתרגם",
    },
    "aramaic_assyrian": {
        "dox_show_more": "ܚܘܝ ܝܬܝܪ",
        "dox_ime": "IME",
        "dox_ime_show": "ܚܘܝ IME",
        "dox_ime_collapse": "ܟܪܘܟ",
        "dox_on": "ܦܬܝܚ",
        "dox_off": "ܕܥܝܟ",
        "dox_auto_translate": "ܬܪܓܡ ܐܘܛܘ",
        "dox_news_to_msa": "ܛܒ̈ܐ → MSA",
        "dox_backend_url": "URL ܕܒܟܢܕ",
        "dox_ime_remember": "ܕܟܪ ܕܘܟܬ IME",
        "dox_ime_enabled": "ܚܘܝ ܣܪܛ IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "ܡܬܚܐ ܡܠܝ. ܢܣܝ ܒܬܪ.",
        "dox_addressee": "ܩܒܘܠܢܐ ܐܢܬ",
        "dox_clear_recents": "ܡܚܝ ܚܕ̈ܬܐ",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "ܥܬܝܕ",
        "dox_status_error": "ܠܐ ܡܨܝܐ ܠܡܬܪܓܡܘ",
        "dox_skip_field": "ܠܐ ܡܨܝܐ ܠܡܬܪܓܡ ܗܢܐ ܚܩܠܐ",
        "dox_default_dialect": "ܠܥܙܐ ܕܫܪܪ",
        "dox_advanced": "ܡܬܩܕܡ",
        "dox_ime_idle": "ܥܬܝܕ",
        "dox_translate_failed": "ܠܐ ܡܨܝܐ ܠܡܬܪܓܡܘ",
    },
    "persian_iran": {
        "dox_show_more": "نمایش بیشتر",
        "dox_ime": "IME",
        "dox_ime_show": "نمایش IME",
        "dox_ime_collapse": "جمع کردن",
        "dox_on": "روشن",
        "dox_off": "خاموش",
        "dox_auto_translate": "ترجمه خودکار",
        "dox_news_to_msa": "اخبار → MSA",
        "dox_backend_url": "نشانی بک‌اند",
        "dox_ime_remember": "موقعیت IME را به خاطر بسپار",
        "dox_ime_enabled": "نوار IME را نشان بده",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "سهمیه تمام شد. بعداً دوباره امتحان کن.",
        "dox_addressee": "مخاطب تو",
        "dox_clear_recents": "پاک کردن موارد اخیر",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "آماده",
        "dox_status_error": "ترجمه نشد",
        "dox_skip_field": "این فیلد ترجمه نمی‌شود",
        "dox_default_dialect": "گویش پیش‌فرض",
        "dox_advanced": "پیشرفته",
        "dox_ime_idle": "آماده",
        "dox_translate_failed": "ترجمه نشد",
    },
    "kurdish_kurmanji": {
        "dox_show_more": "Zêdetir nîşan bide",
        "dox_ime": "IME",
        "dox_ime_show": "IME nîşan bide",
        "dox_ime_collapse": "Bigire",
        "dox_on": "Vekirî",
        "dox_off": "Girtî",
        "dox_auto_translate": "Wergera xweber",
        "dox_news_to_msa": "Nûçe → MSA",
        "dox_backend_url": "URL ya backend",
        "dox_ime_remember": "Cihê IME bi bîr bîne",
        "dox_ime_enabled": "Darika IME nîşan bide",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Sînor tije. Paşê dîsa biceribîne.",
        "dox_addressee": "Wergir tu",
        "dox_clear_recents": "Yên dawî paqij bike",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Amade",
        "dox_status_error": "Werger nehat kirin",
        "dox_skip_field": "Ev qad nayê wergerandin",
        "dox_default_dialect": "Zargotin a standard",
        "dox_advanced": "Pêşketî",
        "dox_ime_idle": "Amade",
        "dox_translate_failed": "Werger nehat kirin",
    },
    "thai_bangkok": {
        "dox_show_more": "แสดงเพิ่ม",
        "dox_ime": "IME",
        "dox_ime_show": "แสดง IME",
        "dox_ime_collapse": "ย่อ",
        "dox_on": "เปิด",
        "dox_off": "ปิด",
        "dox_auto_translate": "แปลอัตโนมัติ",
        "dox_news_to_msa": "ข่าว → MSA",
        "dox_backend_url": "URL แบ็กเอนด์",
        "dox_ime_remember": "จำตำแหน่ง IME",
        "dox_ime_enabled": "แสดงแถบ IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "ถึงโควตาแล้ว ลองใหม่ภายหลัง",
        "dox_addressee": "ผู้รับ คุณ",
        "dox_clear_recents": "ล้างรายการล่าสุด",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "พร้อม",
        "dox_status_error": "แปลไม่ได้",
        "dox_skip_field": "แปลช่องนี้ไม่ได้",
        "dox_default_dialect": "ภาษาถิ่นเริ่มต้น",
        "dox_advanced": "ขั้นสูง",
        "dox_ime_idle": "พร้อม",
        "dox_translate_failed": "แปลไม่ได้",
    },
    "vietnamese_hanoi": {
        "dox_show_more": "Hiện thêm",
        "dox_ime": "IME",
        "dox_ime_show": "Hiện IME",
        "dox_ime_collapse": "Thu gọn",
        "dox_on": "Bật",
        "dox_off": "Tắt",
        "dox_auto_translate": "Tự dịch",
        "dox_news_to_msa": "Tin → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Nhớ vị trí IME",
        "dox_ime_enabled": "Hiện thanh IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Hết hạn mức. Thử lại sau.",
        "dox_addressee": "Người nhận bạn",
        "dox_clear_recents": "Xóa gần đây",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Sẵn sàng",
        "dox_status_error": "Không dịch được",
        "dox_skip_field": "Không dịch được ô này",
        "dox_default_dialect": "Phương ngữ mặc định",
        "dox_advanced": "Nâng cao",
        "dox_ime_idle": "Sẵn sàng",
        "dox_translate_failed": "Không dịch được",
    },
    "filipino_tagalog": {
        "dox_show_more": "Magpakita pa",
        "dox_ime": "IME",
        "dox_ime_show": "Ipakita ang IME",
        "dox_ime_collapse": "I-collapse",
        "dox_on": "Naka-on",
        "dox_off": "Naka-off",
        "dox_auto_translate": "Auto-translate",
        "dox_news_to_msa": "Balita → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "Tandaan ang posisyon ng IME",
        "dox_ime_enabled": "Ipakita ang IME bar",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Naabot ang limit. Subukan ulit mamaya.",
        "dox_addressee": "Kinakausap ikaw",
        "dox_clear_recents": "I-clear ang Recents",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Handa",
        "dox_status_error": "Hindi naisalin",
        "dox_skip_field": "Hindi maisalin ang field na ito",
        "dox_default_dialect": "Default na dayalekto",
        "dox_advanced": "Advanced",
        "dox_ime_idle": "Handa",
        "dox_translate_failed": "Hindi naisalin",
    },
    "malay_malaysia": {
        "dox_show_more": "Tunjuk lagi",
        "dox_ime": "IME",
        "dox_ime_show": "Tunjuk IME",
        "dox_ime_collapse": "Kuncupkan",
        "dox_on": "Hidup",
        "dox_off": "Mati",
        "dox_auto_translate": "Terjemah auto",
        "dox_news_to_msa": "Berita → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Ingat kedudukan IME",
        "dox_ime_enabled": "Tunjuk bar IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Had tercapai. Cuba lagi kemudian.",
        "dox_addressee": "Penerima awak",
        "dox_clear_recents": "Kosongkan terkini",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Sedia",
        "dox_status_error": "Tidak dapat menterjemah",
        "dox_skip_field": "Medan ini tidak boleh diterjemah",
        "dox_default_dialect": "Dialek lalai",
        "dox_advanced": "Lanjutan",
        "dox_ime_idle": "Sedia",
        "dox_translate_failed": "Tidak dapat menterjemah",
    },
    "indonesian_standard": {
        "dox_show_more": "Tampilkan lagi",
        "dox_ime": "IME",
        "dox_ime_show": "Tampilkan IME",
        "dox_ime_collapse": "Ciutkan",
        "dox_on": "Aktif",
        "dox_off": "Nonaktif",
        "dox_auto_translate": "Terjemahan otomatis",
        "dox_news_to_msa": "Berita → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Ingat posisi IME",
        "dox_ime_enabled": "Tampilkan bilah IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Batas tercapai. Coba lagi nanti.",
        "dox_addressee": "Lawannya kamu",
        "dox_clear_recents": "Hapus terbaru",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Siap",
        "dox_status_error": "Gagal menerjemahkan",
        "dox_skip_field": "Kolom ini tidak bisa diterjemahkan",
        "dox_default_dialect": "Dialek default",
        "dox_advanced": "Lanjutan",
        "dox_ime_idle": "Siap",
        "dox_translate_failed": "Gagal menerjemahkan",
    },
    "mongolian_ulaanbaatar": {
        "dox_show_more": "Илүү харах",
        "dox_ime": "IME",
        "dox_ime_show": "IME харуулах",
        "dox_ime_collapse": "Хураах",
        "dox_on": "Асаах",
        "dox_off": "Унтраах",
        "dox_auto_translate": "Авто орчуулга",
        "dox_news_to_msa": "Мэдээ → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME байрлалыг сана",
        "dox_ime_enabled": "IME мөрийг харуул",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Хязгаар хүрлээ. Дараа дахин оролд.",
        "dox_addressee": "Хүлээн авагч чи",
        "dox_clear_recents": "Сүүлийг цэвэрлэх",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Бэлэн",
        "dox_status_error": "Орчуулж чадсангүй",
        "dox_skip_field": "Энэ талбарыг орчуулахгүй",
        "dox_default_dialect": "Үндсэн аялга",
        "dox_advanced": "Дэлгэрэнгүй",
        "dox_ime_idle": "Бэлэн",
        "dox_translate_failed": "Орчуулж чадсангүй",
    },
    "swahili_tanzania": {
        "dox_show_more": "Onyesha zaidi",
        "dox_ime": "IME",
        "dox_ime_show": "Onyesha IME",
        "dox_ime_collapse": "Kunja",
        "dox_on": "Washa",
        "dox_off": "Zima",
        "dox_auto_translate": "Tafsiri otomatiki",
        "dox_news_to_msa": "Habari → MSA",
        "dox_backend_url": "URL ya backend",
        "dox_ime_remember": "Kumbuka nafasi ya IME",
        "dox_ime_enabled": "Onyesha upau wa IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Kikomo kimefikiwa. Jaribu tena baadaye.",
        "dox_addressee": "Mpokeaji wewe",
        "dox_clear_recents": "Futa za hivi karibuni",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Tayari",
        "dox_status_error": "Imeshindwa kutafsiri",
        "dox_skip_field": "Sehemu hii haitafsiriwi",
        "dox_default_dialect": "Lahaja chaguomsingi",
        "dox_advanced": "Zaidi",
        "dox_ime_idle": "Tayari",
        "dox_translate_failed": "Imeshindwa kutafsiri",
    },
    "zulu_standard": {
        "dox_show_more": "Bonisa okuningi",
        "dox_ime": "IME",
        "dox_ime_show": "Bonisa i-IME",
        "dox_ime_collapse": "Goqa",
        "dox_on": "Vuliwe",
        "dox_off": "Cishiwe",
        "dox_auto_translate": "Humusha okuzenzakalelayo",
        "dox_news_to_msa": "Izindaba → MSA",
        "dox_backend_url": "I-URL ye-backend",
        "dox_ime_remember": "Khumbula indawo ye-IME",
        "dox_ime_enabled": "Bonisa ibha ye-IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Umkhawulo ufinyelele. Zama kamuva.",
        "dox_addressee": "Umamukeli wena",
        "dox_clear_recents": "Sula okwakamuva",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Kulungile",
        "dox_status_error": "Ayikwazanga ukuhumusha",
        "dox_skip_field": "Le nsimu ayihunyushwa",
        "dox_default_dialect": "Ulimi lwendabuko olumisiwe",
        "dox_advanced": "Okuthuthukile",
        "dox_ime_idle": "Kulungile",
        "dox_translate_failed": "Ayikwazanga ukuhumusha",
    },
    "serbian_belgrade": {
        "dox_show_more": "Прикажи још",
        "dox_ime": "IME",
        "dox_ime_show": "Прикажи IME",
        "dox_ime_collapse": "Скупи",
        "dox_on": "Укљ.",
        "dox_off": "Искљ.",
        "dox_auto_translate": "Ауто-превод",
        "dox_news_to_msa": "Вести → MSA",
        "dox_backend_url": "URL бекенда",
        "dox_ime_remember": "Запамти положај IME",
        "dox_ime_enabled": "Прикажи IME траку",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Лимит је достигнут. Покушај касније.",
        "dox_addressee": "Саговорник ти",
        "dox_clear_recents": "Обриши недавне",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Спремно",
        "dox_status_error": "Превод није успео",
        "dox_skip_field": "Ово поље се не преводи",
        "dox_default_dialect": "Подразумевани дијалект",
        "dox_advanced": "Напредно",
        "dox_ime_idle": "Спремно",
        "dox_translate_failed": "Превод није успео",
    },
    "croatian_zagreb": {
        "dox_show_more": "Prikaži više",
        "dox_ime": "IME",
        "dox_ime_show": "Prikaži IME",
        "dox_ime_collapse": "Sažmi",
        "dox_on": "Uključeno",
        "dox_off": "Isključeno",
        "dox_auto_translate": "Auto-prijevod",
        "dox_news_to_msa": "Vijesti → MSA",
        "dox_backend_url": "URL backenda",
        "dox_ime_remember": "Zapamti položaj IME",
        "dox_ime_enabled": "Prikaži IME traku",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Dosegnut je limit. Pokušaj kasnije.",
        "dox_addressee": "Sugovornik ti",
        "dox_clear_recents": "Obriši nedavne",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Spremno",
        "dox_status_error": "Prijevod nije uspio",
        "dox_skip_field": "Ovo polje se ne prevodi",
        "dox_default_dialect": "Zadani dijalekt",
        "dox_advanced": "Napredno",
        "dox_ime_idle": "Spremno",
        "dox_translate_failed": "Prijevod nije uspio",
    },
    "bosnian_sarajevo": {
        "dox_show_more": "Prikaži više",
        "dox_ime": "IME",
        "dox_ime_show": "Prikaži IME",
        "dox_ime_collapse": "Skupi",
        "dox_on": "Uključeno",
        "dox_off": "Isključeno",
        "dox_auto_translate": "Auto-prijevod",
        "dox_news_to_msa": "Vijesti → MSA",
        "dox_backend_url": "URL backenda",
        "dox_ime_remember": "Zapamti položaj IME",
        "dox_ime_enabled": "Prikaži IME traku",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit je dostignut. Pokušaj kasnije.",
        "dox_addressee": "Sagovornik ti",
        "dox_clear_recents": "Obriši nedavne",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Spremno",
        "dox_status_error": "Prijevod nije uspio",
        "dox_skip_field": "Ovo polje se ne prevodi",
        "dox_default_dialect": "Zadani dijalekt",
        "dox_advanced": "Napredno",
        "dox_ime_idle": "Spremno",
        "dox_translate_failed": "Prijevod nije uspio",
    },
    "bulgarian_sofia": {
        "dox_show_more": "Покажи още",
        "dox_ime": "IME",
        "dox_ime_show": "Покажи IME",
        "dox_ime_collapse": "Свий",
        "dox_on": "Вкл.",
        "dox_off": "Изкл.",
        "dox_auto_translate": "Автопревод",
        "dox_news_to_msa": "Новини → MSA",
        "dox_backend_url": "URL на бекенда",
        "dox_ime_remember": "Запомни позицията на IME",
        "dox_ime_enabled": "Покажи лентата IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Лимитът е достигнат. Опитай по-късно.",
        "dox_addressee": "Адресат ти",
        "dox_clear_recents": "Изчисти скорошни",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Готово",
        "dox_status_error": "Неуспешен превод",
        "dox_skip_field": "Това поле не се превежда",
        "dox_default_dialect": "Диалект по подразбиране",
        "dox_advanced": "Разширени",
        "dox_ime_idle": "Готово",
        "dox_translate_failed": "Неуспешен превод",
    },
    "macedonian_skopje": {
        "dox_show_more": "Прикажи повеќе",
        "dox_ime": "IME",
        "dox_ime_show": "Прикажи IME",
        "dox_ime_collapse": "Собери",
        "dox_on": "Вкл.",
        "dox_off": "Искл.",
        "dox_auto_translate": "Автопревод",
        "dox_news_to_msa": "Вести → MSA",
        "dox_backend_url": "URL на бекендот",
        "dox_ime_remember": "Запомни положба на IME",
        "dox_ime_enabled": "Прикажи лента IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Лимитот е достигнат. Обиди се подоцна.",
        "dox_addressee": "Адресат ти",
        "dox_clear_recents": "Избриши скорешни",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Подготвено",
        "dox_status_error": "Неуспешен превод",
        "dox_skip_field": "Ова поле не се преведува",
        "dox_default_dialect": "Стандарден дијалект",
        "dox_advanced": "Напредно",
        "dox_ime_idle": "Подготвено",
        "dox_translate_failed": "Неуспешен превод",
    },
    "slovenian_ljubljana": {
        "dox_show_more": "Prikaži več",
        "dox_ime": "IME",
        "dox_ime_show": "Prikaži IME",
        "dox_ime_collapse": "Strni",
        "dox_on": "Vklopljeno",
        "dox_off": "Izklopljeno",
        "dox_auto_translate": "Samodejni prevod",
        "dox_news_to_msa": "Novice → MSA",
        "dox_backend_url": "URL zaledja",
        "dox_ime_remember": "Zapomni si položaj IME",
        "dox_ime_enabled": "Prikaži vrstico IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit dosežen. Poskusi pozneje.",
        "dox_addressee": "Naslovljenec ti",
        "dox_clear_recents": "Počisti nedavno",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Pripravljeno",
        "dox_status_error": "Prevajanje ni uspelo",
        "dox_skip_field": "Tega polja ni mogoče prevesti",
        "dox_default_dialect": "Privzeto narečje",
        "dox_advanced": "Napredno",
        "dox_ime_idle": "Pripravljeno",
        "dox_translate_failed": "Prevajanje ni uspelo",
    },
    "albanian_tirana": {
        "dox_show_more": "Shfaq më shumë",
        "dox_ime": "IME",
        "dox_ime_show": "Shfaq IME",
        "dox_ime_collapse": "Palos",
        "dox_on": "Ndezur",
        "dox_off": "Fikur",
        "dox_auto_translate": "Përkthim auto",
        "dox_news_to_msa": "Lajme → MSA",
        "dox_backend_url": "URL e backend",
        "dox_ime_remember": "Kujto pozicionin e IME",
        "dox_ime_enabled": "Shfaq shiritin IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "U arrit kufiri. Provo më vonë.",
        "dox_addressee": "Adresuesi ti",
        "dox_clear_recents": "Pastro të fundit",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Gati",
        "dox_status_error": "Nuk u përkthye",
        "dox_skip_field": "Kjo fushë nuk përkthehet",
        "dox_default_dialect": "Dialekti i paracaktuar",
        "dox_advanced": "Të përparuara",
        "dox_ime_idle": "Gati",
        "dox_translate_failed": "Nuk u përkthye",
    },
    "greek_athens": {
        "dox_show_more": "Εμφάνιση περισσότερων",
        "dox_ime": "IME",
        "dox_ime_show": "Εμφάνιση IME",
        "dox_ime_collapse": "Σύμπτυξη",
        "dox_on": "Ενεργό",
        "dox_off": "Ανενεργό",
        "dox_auto_translate": "Αυτόματη μετάφραση",
        "dox_news_to_msa": "Ειδήσεις → MSA",
        "dox_backend_url": "URL backend",
        "dox_ime_remember": "Απομνημόνευση θέσης IME",
        "dox_ime_enabled": "Εμφάνιση μπάρας IME",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Φτάσατε το όριο. Δοκιμάστε αργότερα.",
        "dox_addressee": "Αποδέκτης εσύ",
        "dox_clear_recents": "Καθαρισμός πρόσφατων",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Έτοιμο",
        "dox_status_error": "Αποτυχία μετάφρασης",
        "dox_skip_field": "Αυτό το πεδίο δεν μεταφράζεται",
        "dox_default_dialect": "Προεπιλεγμένη διάλεκτος",
        "dox_advanced": "Για προχωρημένους",
        "dox_ime_idle": "Έτοιμο",
        "dox_translate_failed": "Αποτυχία μετάφρασης",
    },
    "swedish_stockholm": {
        "dox_show_more": "Visa mer",
        "dox_ime": "IME",
        "dox_ime_show": "Visa IME",
        "dox_ime_collapse": "Fäll ihop",
        "dox_on": "På",
        "dox_off": "Av",
        "dox_auto_translate": "Autoöversätt",
        "dox_news_to_msa": "Nyheter → MSA",
        "dox_backend_url": "Backend-URL",
        "dox_ime_remember": "Kom ihåg IME-läge",
        "dox_ime_enabled": "Visa IME-rad",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Gränsen nådd. Försök igen senare.",
        "dox_addressee": "Tilltal du",
        "dox_clear_recents": "Rensa senaste",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Redo",
        "dox_status_error": "Kunde inte översätta",
        "dox_skip_field": "Det här fältet kan inte översättas",
        "dox_default_dialect": "Standarddialekt",
        "dox_advanced": "Avancerat",
        "dox_ime_idle": "Redo",
        "dox_translate_failed": "Kunde inte översätta",
    },
    "norwegian_oslo": {
        "dox_show_more": "Vis mer",
        "dox_ime": "IME",
        "dox_ime_show": "Vis IME",
        "dox_ime_collapse": "Skjul",
        "dox_on": "På",
        "dox_off": "Av",
        "dox_auto_translate": "Auto-oversett",
        "dox_news_to_msa": "Nyheter → MSA",
        "dox_backend_url": "Backend-URL",
        "dox_ime_remember": "Husk IME-posisjon",
        "dox_ime_enabled": "Vis IME-linje",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Grense nådd. Prøv igjen senere.",
        "dox_addressee": "Mottaker du",
        "dox_clear_recents": "Tøm nylige",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Klar",
        "dox_status_error": "Klarte ikke å oversette",
        "dox_skip_field": "Dette feltet kan ikke oversettes",
        "dox_default_dialect": "Standarddialekt",
        "dox_advanced": "Avansert",
        "dox_ime_idle": "Klar",
        "dox_translate_failed": "Klarte ikke å oversette",
    },
    "danish_copenhagen": {
        "dox_show_more": "Vis mere",
        "dox_ime": "IME",
        "dox_ime_show": "Vis IME",
        "dox_ime_collapse": "Skjul",
        "dox_on": "Til",
        "dox_off": "Fra",
        "dox_auto_translate": "Auto-oversæt",
        "dox_news_to_msa": "Nyheder → MSA",
        "dox_backend_url": "Backend-URL",
        "dox_ime_remember": "Husk IME-position",
        "dox_ime_enabled": "Vis IME-bjælke",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Grænse nået. Prøv igen senere.",
        "dox_addressee": "Modtager du",
        "dox_clear_recents": "Ryd seneste",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Klar",
        "dox_status_error": "Kunne ikke oversætte",
        "dox_skip_field": "Dette felt kan ikke oversættes",
        "dox_default_dialect": "Standarddialekt",
        "dox_advanced": "Avanceret",
        "dox_ime_idle": "Klar",
        "dox_translate_failed": "Kunne ikke oversætte",
    },
    "icelandic_reykjavik": {
        "dox_show_more": "Sýna meira",
        "dox_ime": "IME",
        "dox_ime_show": "Sýna IME",
        "dox_ime_collapse": "Fella saman",
        "dox_on": "Kveikt",
        "dox_off": "Slökkt",
        "dox_auto_translate": "Sjálfvirk þýðing",
        "dox_news_to_msa": "Fréttir → MSA",
        "dox_backend_url": "Backend-slóð",
        "dox_ime_remember": "Muna IME-staðsetningu",
        "dox_ime_enabled": "Sýna IME-stiku",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Takmarki náð. Reyndu síðar.",
        "dox_addressee": "Viðtakandi þú",
        "dox_clear_recents": "Hreinsa nýlegt",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Tilbúið",
        "dox_status_error": "Gat ekki þýtt",
        "dox_skip_field": "Þennan reit er ekki hægt að þýða",
        "dox_default_dialect": "Sjálfgefinn mállýska",
        "dox_advanced": "Ítarlegt",
        "dox_ime_idle": "Tilbúið",
        "dox_translate_failed": "Gat ekki þýtt",
    },
    "finnish_helsinki": {
        "dox_show_more": "Näytä lisää",
        "dox_ime": "IME",
        "dox_ime_show": "Näytä IME",
        "dox_ime_collapse": "Pienennä",
        "dox_on": "Päällä",
        "dox_off": "Pois",
        "dox_auto_translate": "Autokäännös",
        "dox_news_to_msa": "Uutiset → MSA",
        "dox_backend_url": "Taustan URL",
        "dox_ime_remember": "Muista IME-sijainti",
        "dox_ime_enabled": "Näytä IME-palkki",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Raja täynnä. Yritä myöhemmin.",
        "dox_addressee": "Puhuteltu sinä",
        "dox_clear_recents": "Tyhjennä viimeisimmät",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Valmis",
        "dox_status_error": "Käännös epäonnistui",
        "dox_skip_field": "Tätä kenttää ei voi kääntää",
        "dox_default_dialect": "Oletusmurre",
        "dox_advanced": "Lisäasetukset",
        "dox_ime_idle": "Valmis",
        "dox_translate_failed": "Käännös epäonnistui",
    },
    "turkish_turkey": {
        "dox_show_more": "Daha fazla göster",
        "dox_ime": "IME",
        "dox_ime_show": "IME'yi göster",
        "dox_ime_collapse": "Daralt",
        "dox_on": "Açık",
        "dox_off": "Kapalı",
        "dox_auto_translate": "Otomatik çevir",
        "dox_news_to_msa": "Haber → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME konumunu hatırla",
        "dox_ime_enabled": "IME çubuğunu göster",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Sınır doldu. Daha sonra dene.",
        "dox_addressee": "Hitap sen",
        "dox_clear_recents": "Son kullanılanları temizle",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Hazır",
        "dox_status_error": "Çevrilemedi",
        "dox_skip_field": "Bu alan çevrilemez",
        "dox_default_dialect": "Varsayılan lehçe",
        "dox_advanced": "Gelişmiş",
        "dox_ime_idle": "Hazır",
        "dox_translate_failed": "Çevrilemedi",
    },
    "kazakh_almaty": {
        "dox_show_more": "Көбірек көрсету",
        "dox_ime": "IME",
        "dox_ime_show": "IME көрсету",
        "dox_ime_collapse": "Жию",
        "dox_on": "Қосулы",
        "dox_off": "Өшірулі",
        "dox_auto_translate": "Автоаударма",
        "dox_news_to_msa": "Жаңалық → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME орнын есте сақта",
        "dox_ime_enabled": "IME жолағын көрсет",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Шекке жетті. Кейінірек қайтала.",
        "dox_addressee": "Алушы сен",
        "dox_clear_recents": "Жуықтағыны тазалау",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Дайын",
        "dox_status_error": "Аударылмады",
        "dox_skip_field": "Бұл өріс аударылмайды",
        "dox_default_dialect": "Әдепкі диалект",
        "dox_advanced": "Қосымша",
        "dox_ime_idle": "Дайын",
        "dox_translate_failed": "Аударылмады",
    },
    "uzbek_tashkent": {
        "dox_show_more": "Ko‘proq ko‘rsat",
        "dox_ime": "IME",
        "dox_ime_show": "IME ni ko‘rsat",
        "dox_ime_collapse": "Yig‘ish",
        "dox_on": "Yon",
        "dox_off": "O‘chiq",
        "dox_auto_translate": "Avto tarjima",
        "dox_news_to_msa": "Yangilik → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME joyini eslab qol",
        "dox_ime_enabled": "IME panelini ko‘rsat",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit tugadi. Keyinroq urinib ko‘ring.",
        "dox_addressee": "Qabul qiluvchi sen",
        "dox_clear_recents": "Yaqindagilarni tozalash",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Tayyor",
        "dox_status_error": "Tarjima bo‘lmadi",
        "dox_skip_field": "Bu maydon tarjima qilinmaydi",
        "dox_default_dialect": "Standart sheva",
        "dox_advanced": "Kengaytirilgan",
        "dox_ime_idle": "Tayyor",
        "dox_translate_failed": "Tarjima bo‘lmadi",
    },
    "kyrgyz_bishkek": {
        "dox_show_more": "Көбүрөөк көрсөт",
        "dox_ime": "IME",
        "dox_ime_show": "IME көрсөт",
        "dox_ime_collapse": "Жый",
        "dox_on": "Күйүк",
        "dox_off": "Өчүк",
        "dox_auto_translate": "Авто котормо",
        "dox_news_to_msa": "Жаңылык → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME ордун эсте",
        "dox_ime_enabled": "IME тилкесин көрсөт",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Чекке жетти. Кийинчерээк кайтала.",
        "dox_addressee": "Алуучу сен",
        "dox_clear_recents": "Акыркыларды тазалоо",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Даяр",
        "dox_status_error": "Которулган жок",
        "dox_skip_field": "Бул талаа которулбайт",
        "dox_default_dialect": "Демейки диалект",
        "dox_advanced": "Кошумча",
        "dox_ime_idle": "Даяр",
        "dox_translate_failed": "Которулган жок",
    },
    "turkmen_ashgabat": {
        "dox_show_more": "Has görkez",
        "dox_ime": "IME",
        "dox_ime_show": "IME görkez",
        "dox_ime_collapse": "Ýygna",
        "dox_on": "Açyk",
        "dox_off": "Ýapyk",
        "dox_auto_translate": "Awto terjime",
        "dox_news_to_msa": "Täzelik → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME ýerini ýatda sakla",
        "dox_ime_enabled": "IME zolagyny görkez",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Çäk doly. Soňrak synanyş.",
        "dox_addressee": "Alyjy sen",
        "dox_clear_recents": "Soňkylary arassala",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Taýýar",
        "dox_status_error": "Terjime bolmady",
        "dox_skip_field": "Bu meýdan terjime edilmeýär",
        "dox_default_dialect": "Deslapky şiwe",
        "dox_advanced": "Giňeldilen",
        "dox_ime_idle": "Taýýar",
        "dox_translate_failed": "Terjime bolmady",
    },
    "azerbaijani_baku": {
        "dox_show_more": "Daha çox göstər",
        "dox_ime": "IME",
        "dox_ime_show": "IME göstər",
        "dox_ime_collapse": "Yığ",
        "dox_on": "Açıq",
        "dox_off": "Bağlı",
        "dox_auto_translate": "Avto tərcümə",
        "dox_news_to_msa": "Xəbər → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME yerini yadda saxla",
        "dox_ime_enabled": "IME zolağını göstər",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limit dolub. Sonra yenidən yoxla.",
        "dox_addressee": "Ünvanlanan sən",
        "dox_clear_recents": "Sonuncuları sil",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Hazır",
        "dox_status_error": "Tərcümə olunmadı",
        "dox_skip_field": "Bu sahə tərcümə olunmur",
        "dox_default_dialect": "Susmaya görə dialekt",
        "dox_advanced": "Əlavə",
        "dox_ime_idle": "Hazır",
        "dox_translate_failed": "Tərcümə olunmadı",
    },
    "hindi_delhi": {
        "dox_show_more": "और दिखाएँ",
        "dox_ime": "IME",
        "dox_ime_show": "IME दिखाएँ",
        "dox_ime_collapse": "समेटें",
        "dox_on": "चालू",
        "dox_off": "बंद",
        "dox_auto_translate": "स्वतः अनुवाद",
        "dox_news_to_msa": "समाचार → MSA",
        "dox_backend_url": "बैकएंड URL",
        "dox_ime_remember": "IME स्थिति याद रखें",
        "dox_ime_enabled": "IME पट्टी दिखाएँ",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "सीमा पूरी। बाद में फिर कोशिश करें।",
        "dox_addressee": "संबोधित आप",
        "dox_clear_recents": "हालिया साफ़ करें",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "तैयार",
        "dox_status_error": "अनुवाद नहीं हो सका",
        "dox_skip_field": "यह फ़ील्ड अनुवाद नहीं हो सकती",
        "dox_default_dialect": "डिफ़ॉल्ट बोली",
        "dox_advanced": "उन्नत",
        "dox_ime_idle": "तैयार",
        "dox_translate_failed": "अनुवाद नहीं हो सका",
    },
    "punjabi_indian": {
        "dox_show_more": "ਹੋਰ ਵਿਖਾਓ",
        "dox_ime": "IME",
        "dox_ime_show": "IME ਵਿਖਾਓ",
        "dox_ime_collapse": "ਸਮੇਟੋ",
        "dox_on": "ਚਾਲੂ",
        "dox_off": "ਬੰਦ",
        "dox_auto_translate": "ਆਪ-ਅਨੁਵਾਦ",
        "dox_news_to_msa": "ਖ਼ਬਰਾਂ → MSA",
        "dox_backend_url": "ਬੈਕਐਂਡ URL",
        "dox_ime_remember": "IME ਸਥਿਤੀ ਯਾਦ ਰੱਖੋ",
        "dox_ime_enabled": "IME ਪੱਟੀ ਵਿਖਾਓ",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "ਹੱਦ ਪੂਰੀ। ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "dox_addressee": "ਸੰਬੋਧਿਤ ਤੂੰ",
        "dox_clear_recents": "ਹਾਲੀਆ ਸਾਫ਼ ਕਰੋ",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "ਤਿਆਰ",
        "dox_status_error": "ਅਨੁਵਾਦ ਨਹੀਂ ਹੋ ਸਕਿਆ",
        "dox_skip_field": "ਇਹ ਖੇਤਰ ਅਨੁਵਾਦ ਨਹੀਂ ਹੋ ਸਕਦਾ",
        "dox_default_dialect": "ਮੂਲ ਉਪਭਾਸ਼ਾ",
        "dox_advanced": "ਉੱਨਤ",
        "dox_ime_idle": "ਤਿਆਰ",
        "dox_translate_failed": "ਅਨੁਵਾਦ ਨਹੀਂ ਹੋ ਸਕਿਆ",
    },
    "telugu_andhra": {
        "dox_show_more": "మరింత చూపించు",
        "dox_ime": "IME",
        "dox_ime_show": "IME చూపించు",
        "dox_ime_collapse": "కుదించు",
        "dox_on": "ఆన్",
        "dox_off": "ఆఫ్",
        "dox_auto_translate": "ఆటో అనువాదం",
        "dox_news_to_msa": "వార్తలు → MSA",
        "dox_backend_url": "బ్యాకెండ్ URL",
        "dox_ime_remember": "IME స్థానం గుర్తుంచుకో",
        "dox_ime_enabled": "IME పట్టీ చూపించు",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "పరిమితి నిండింది. తర్వాత ప్రయత్నించండి.",
        "dox_addressee": "సంబోధిత నువ్వు",
        "dox_clear_recents": "ఇటీవలివి తొలగించు",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "సిద్ధం",
        "dox_status_error": "అనువదించలేకపోయాం",
        "dox_skip_field": "ఈ ఫీల్డ్ అనువదించలేం",
        "dox_default_dialect": "డిఫాల్ట్ మాండలికం",
        "dox_advanced": "అధునాతనం",
        "dox_ime_idle": "సిద్ధం",
        "dox_translate_failed": "అనువదించలేకపోయాం",
    },
    "tamil_chennai": {
        "dox_show_more": "மேலும் காட்டு",
        "dox_ime": "IME",
        "dox_ime_show": "IME காட்டு",
        "dox_ime_collapse": "சுருக்கு",
        "dox_on": "இயக்கு",
        "dox_off": "அணை",
        "dox_auto_translate": "தானியங்கி மொழிபெயர்ப்பு",
        "dox_news_to_msa": "செய்தி → MSA",
        "dox_backend_url": "பின்புல URL",
        "dox_ime_remember": "IME இடத்தை நினைவில் கொள்",
        "dox_ime_enabled": "IME பட்டியைக் காட்டு",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "வரம்பு நிறைந்தது. பின்னர் முயல்க.",
        "dox_addressee": "பேசப்படும் நீ",
        "dox_clear_recents": "சமீபத்தியவற்றை அழி",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "தயார்",
        "dox_status_error": "மொழிபெயர்க்க முடியவில்லை",
        "dox_skip_field": "இந்தப் புலத்தை மொழிபெயர்க்க முடியாது",
        "dox_default_dialect": "இயல்பு பேச்சுவழக்கு",
        "dox_advanced": "மேம்பட்டவை",
        "dox_ime_idle": "தயார்",
        "dox_translate_failed": "மொழிபெயர்க்க முடியவில்லை",
    },
    "urdu_pakistani": {
        "dox_show_more": "مزید دکھائیں",
        "dox_ime": "IME",
        "dox_ime_show": "IME دکھائیں",
        "dox_ime_collapse": "سمیٹیں",
        "dox_on": "آن",
        "dox_off": "آف",
        "dox_auto_translate": "خودکار ترجمہ",
        "dox_news_to_msa": "خبریں → MSA",
        "dox_backend_url": "بیک اینڈ URL",
        "dox_ime_remember": "IME مقام یاد رکھیں",
        "dox_ime_enabled": "IME بار دکھائیں",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "حد پوری ہو گئی۔ بعد میں کوشش کریں۔",
        "dox_addressee": "مخاطب آپ",
        "dox_clear_recents": "حالیہ صاف کریں",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "تیار",
        "dox_status_error": "ترجمہ نہ ہو سکا",
        "dox_skip_field": "یہ خانہ ترجمہ نہیں ہو سکتا",
        "dox_default_dialect": "طے شدہ بولی",
        "dox_advanced": "اعلیٰ",
        "dox_ime_idle": "تیار",
        "dox_translate_failed": "ترجمہ نہ ہو سکا",
    },
    "nepali_kathmandu": {
        "dox_show_more": "थप देखाउनुहोस्",
        "dox_ime": "IME",
        "dox_ime_show": "IME देखाउनुहोस्",
        "dox_ime_collapse": "संक्षिप्त पार्नुहोस्",
        "dox_on": "अन",
        "dox_off": "अफ",
        "dox_auto_translate": "स्वतः अनुवाद",
        "dox_news_to_msa": "समाचार → MSA",
        "dox_backend_url": "ब्याकएन्ड URL",
        "dox_ime_remember": "IME स्थान सम्झनुहोस्",
        "dox_ime_enabled": "IME पट्टी देखाउनुहोस्",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "सीमा पुग्यो। पछि फेरि प्रयास गर्नुहोस्।",
        "dox_addressee": "सम्बोधन तपाईं",
        "dox_clear_recents": "हालसालै मेटाउनुहोस्",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "तयार",
        "dox_status_error": "अनुवाद हुन सकेन",
        "dox_skip_field": "यो फिल्ड अनुवाद हुँदैन",
        "dox_default_dialect": "पूर्वनिर्धारित बोली",
        "dox_advanced": "उन्नत",
        "dox_ime_idle": "तयार",
        "dox_translate_failed": "अनुवाद हुन सकेन",
    },
    "lithuanian_vilnius": {
        "dox_show_more": "Rodyti daugiau",
        "dox_ime": "IME",
        "dox_ime_show": "Rodyti IME",
        "dox_ime_collapse": "Sutraukti",
        "dox_on": "Įjungta",
        "dox_off": "Išjungta",
        "dox_auto_translate": "Automatinis vertimas",
        "dox_news_to_msa": "Naujienos → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "Įsiminti IME vietą",
        "dox_ime_enabled": "Rodyti IME juostą",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limitas pasiektas. Bandykite vėliau.",
        "dox_addressee": "Adresatas tu",
        "dox_clear_recents": "Išvalyti paskiausius",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Paruošta",
        "dox_status_error": "Nepavyko išversti",
        "dox_skip_field": "Šio lauko versti negalima",
        "dox_default_dialect": "Numatytoji tarmė",
        "dox_advanced": "Išplėstiniai",
        "dox_ime_idle": "Paruošta",
        "dox_translate_failed": "Nepavyko išversti",
    },
    "latvian_riga": {
        "dox_show_more": "Rādīt vairāk",
        "dox_ime": "IME",
        "dox_ime_show": "Rādīt IME",
        "dox_ime_collapse": "Sakļaut",
        "dox_on": "Ieslēgts",
        "dox_off": "Izslēgts",
        "dox_auto_translate": "Auto tulkojums",
        "dox_news_to_msa": "Ziņas → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "Atcerēties IME pozīciju",
        "dox_ime_enabled": "Rādīt IME joslu",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Limits sasniegts. Mēģini vēlāk.",
        "dox_addressee": "Adresāts tu",
        "dox_clear_recents": "Notīrīt nesenos",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Gatavs",
        "dox_status_error": "Neizdevās tulkot",
        "dox_skip_field": "Šo lauku nevar tulkot",
        "dox_default_dialect": "Noklusējuma dialekts",
        "dox_advanced": "Papildu",
        "dox_ime_idle": "Gatavs",
        "dox_translate_failed": "Neizdevās tulkot",
    },
    "georgian_tbilisi": {
        "dox_show_more": "მეტის ჩვენება",
        "dox_ime": "IME",
        "dox_ime_show": "IME-ის ჩვენება",
        "dox_ime_collapse": "ჩაკეცვა",
        "dox_on": "ჩართული",
        "dox_off": "გამორთული",
        "dox_auto_translate": "ავტოთარგმნა",
        "dox_news_to_msa": "სიახლე → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "IME პოზიციის დამახსოვრება",
        "dox_ime_enabled": "IME ზოლის ჩვენება",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "ლიმიტი ამოიწურა. სცადე მოგვიანებით.",
        "dox_addressee": "ადრესატი შენ",
        "dox_clear_recents": "ბოლოების გასუფთავება",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "მზადაა",
        "dox_status_error": "თარგმნა ვერ მოხერხდა",
        "dox_skip_field": "ეს ველი არ ითარგმნება",
        "dox_default_dialect": "ნაგულისხმევი დიალექტი",
        "dox_advanced": "დამატებითი",
        "dox_ime_idle": "მზადაა",
        "dox_translate_failed": "თარგმნა ვერ მოხერხდა",
    },
    "armenian_yerevan": {
        "dox_show_more": "Ցույց տալ ավելին",
        "dox_ime": "IME",
        "dox_ime_show": "Ցույց տալ IME",
        "dox_ime_collapse": "Ծալել",
        "dox_on": "Միացված",
        "dox_off": "Անջատված",
        "dox_auto_translate": "Ինքնաթարգմանում",
        "dox_news_to_msa": "Լուրեր → MSA",
        "dox_backend_url": "Backend URL",
        "dox_ime_remember": "Հիշել IME դիրքը",
        "dox_ime_enabled": "Ցույց տալ IME գոտին",
        "dox_open_pad": "Dialex Pad",
        "dox_rate_limited": "Սահմանը լրացավ։ Փորձիր հետո։",
        "dox_addressee": "Հասցեատեր դու",
        "dox_clear_recents": "Մաքրել վերջինները",
        "dox_about_line": "DialectsOnX %1$s",
        "dox_status_ready": "Պատրաստ",
        "dox_status_error": "Չհաջողվեց թարգմանել",
        "dox_skip_field": "Այս դաշտը չի թարգմանվում",
        "dox_default_dialect": "Լռելյայն բարբառ",
        "dox_advanced": "Ընդլայնված",
        "dox_ime_idle": "Պատրաստ",
        "dox_translate_failed": "Չհաջողվեց թարգմանել",
    },
}


def delta_for(dialect_id: str) -> dict[str, str]:
    if dialect_id == "english_american":
        return dict(DELTA_EN)
    packed = DELTA_BY_DIALECT.get(dialect_id)
    if not packed:
        raise KeyError(f"missing DialectsOnX delta for {dialect_id}")
    missing = [k for k in DELTA_EN if k not in packed]
    if missing:
        raise KeyError(f"{dialect_id} missing delta keys {missing}")
    extra = [k for k in packed if k not in DELTA_EN]
    if extra:
        raise KeyError(f"{dialect_id} extra delta keys {extra}")
    return dict(packed)
